services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    networks:
      - admin
      - apps
    environment:
      - PUID=0
      - PGID=0
      - TZ=$TZ
      # - CLI_ARGS= #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $APPDIR/duplicati:/config
      - $DOCKERDIR/backups:/backups
      - $APPDIR:/source
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - 8200:8200
    restart: unless-stopped