services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5690"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - apps
    ports:
      - 5690:5690
    volumes:
      - $APPDIR/wizarr:/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DISABLE_BUILTIN_AUTH=false
